name: webmethods-microservicesruntime-wpm-demo

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    tags:
      - 'v*'

env:
  
  BUILD_REGISTRY: ghcr.io
  
  # ${{ github.repository }} = <account>/<repo>
  # ${{ github.workflow }} = name of the workflow
  BUILD_IMAGE_NAME: ${{ github.repository }}

  WEBMETHODS_BASE_REGISTRY: ibmwebmethods.azurecr.io
  WEBMETHODS_BASE_REPOSITORY: webmethods-microservicesruntime
  WEBMETHODS_BASE_TAG: "11.1.0.5"
  WPM_PACKAGES: WmJDBCAdapter:v10.3.8.21 WmMQAdapter:v6.5.5.52 WmCloudStreams:v11.1.0

jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to webMethods container registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.WEBMETHODS_BASE_REGISTRY }}
          username: ${{ secrets.ibmwmcr-username }}
          password: ${{ secrets.ibmwmcr-password }}
      
      # Login against a github registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.BUILD_REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.BUILD_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.BUILD_REGISTRY }}/${{ github.repository_owner }}/${{ env.BUILD_IMAGE_NAME }}
          tags: |
            type=sha
            type=match,pattern=v(.*),group=1
  
      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          build-args: |
            BASE_IMAGE=${{ env.WEBMETHODS_BASE_REGISTRY }}/${{ env.WEBMETHODS_BASE_REPOSITORY }}:${{ env.WEBMETHODS_BASE_TAG }}
            WPM_TOKEN=${{ secrets.WPM_TOKEN }}
            WPM_PACKAGES=${{ env.WPM_PACKAGES }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}